import { useState } from "react";
import Button from "react-bootstrap/Button";
import Modal from "react-bootstrap/Modal";
import Form from "react-bootstrap/Form";
import { useFetch } from "../../hooks/useFetch";
import { api } from "../../api/client";
import { Loading, ErrorAlert } from "../../components/Feedback";
import PageHeader from "../../components/PageHeader";
import DataTable from "../../components/DataTable";

const STATS_TYPES = ["Attendance Summary", "Performance Average", "Participation count", "Training performance"];

export default function AdminStatistics() {
  const { data: stats, loading, error, reload } = useFetch("/admin/statistics");
  const [show, setShow] = useState(false);
  const [statsType, setStatsType] = useState(STATS_TYPES[0]);
  const [description, setDescription] = useState("");
  const [formError, setFormError] = useState("");
  const [submitting, setSubmitting] = useState(false);

  async function handleGenerate(e) {
    e.preventDefault();
    setFormError("");
    setSubmitting(true);
    try {
      await api.post("/admin/statistics", { stats_type: statsType, description: description.trim() || undefined });
      setShow(false);
      setDescription("");
      reload();
    } catch (err) {
      setFormError(err.message);
    } finally {
      setSubmitting(false);
    }
  }

  const columns = [
    { key: "stats_type", label: "Type" },
    { key: "data_payload", label: "Result" },
    { key: "description", label: "Description", render: (r) => r.description || "—" },
    { key: "generated_by_name", label: "Generated by" },
    { key: "generated_date", label: "Generated" },
  ];

  return (
    <div>
      <PageHeader
        title="Statistics"
        subtitle="Computed statistics from live attendance, evaluation, and participation data."
        actions={
          <Button size="sm" onClick={() => setShow(true)}>
            Generate statistic
          </Button>
        }
      />
      <ErrorAlert message={error} />
      {loading ? <Loading /> : <DataTable columns={columns} rows={stats} emptyMessage="No statistics generated yet." />}

      <Modal show={show} onHide={() => setShow(false)} centered>
        <Modal.Header closeButton>
          <Modal.Title className="h6">Generate statistic</Modal.Title>
        </Modal.Header>
        <Form onSubmit={handleGenerate}>
          <Modal.Body>
            <ErrorAlert message={formError} />
            <Form.Group className="mb-3">
              <Form.Label>Type</Form.Label>
              <Form.Select value={statsType} onChange={(e) => setStatsType(e.target.value)}>
                {STATS_TYPES.map((t) => (
                  <option key={t} value={t}>
                    {t}
                  </option>
                ))}
              </Form.Select>
            </Form.Group>
            <Form.Group>
              <Form.Label>Description (optional)</Form.Label>
              <Form.Control
                as="textarea"
                rows={2}
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Note about why this was generated…"
              />
            </Form.Group>
          </Modal.Body>
          <Modal.Footer>
            <Button variant="outline-secondary" onClick={() => setShow(false)} disabled={submitting}>
              Cancel
            </Button>
            <Button type="submit" disabled={submitting}>
              {submitting ? "Generating…" : "Generate"}
            </Button>
          </Modal.Footer>
        </Form>
      </Modal>
    </div>
  );
}
